work on maintainer scripts: - remove preinst and prerm because they were empty - put everything in postint into 'config' argument, since that's   really what it is - make sure deletion of monkeysphere user is correct, based on what we   found here: http://wiki.debian.org/AccountHandlingInMaintainerScripts

diff --git a/packaging/debian/monkeysphere.postrm b/packaging/debian/monkeysphere.postrm
--- a/packaging/debian/monkeysphere.postrm
+++ b/packaging/debian/monkeysphere.postrm
@@ -7,8 +7,13 @@
 
 case $1 in
     purge)
-        echo "removing monkeysphere user..."
-        userdel monkeysphere > /dev/null || true
+	# delete monkeysphere user
+	# http://wiki.debian.org/AccountHandlingInMaintainerScripts
+	if type deluser >/dev/null 2>&1; then
+	    deluser --quiet --system monkeysphere > /dev/null || true
+	else
+	    echo >&2 "not removing monkeysphere system account because deluser command was not found"
+	fi
         ;;
 esac
 
